---
title: | 
  | Atlas de Espacios Verdes e Índice de Accesibilidad en Ciudades Argentinas
author: "Antonio Vázquez Brust"
date: "`r format(Sys.time(), '%d de %B, %Y')`"
output:
  pdf_document: default
  html_document: default
subtitle: Informe de Avance
abstract: Reporte con el progreso del proyecto "Atlas de Espacios Verdes en Ciudadades Argentinas", realizado en el marco del programa *Ciudades Argentinas Sostenibles e Inclusivas*, de la Fundación Bunge y Born, con apoyo del Fondo para la Conservación Ambiental (FOCA) 10^ma^ edición - "Biodiversidad, Energía y Ambientes Urbanos"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
options(scipen = 20)
```


## Problemática ambiental abordada

Entre los 17 Objetivos del Desarrollo Sostenible fijados por Naciones Unidas, el onceavo trata de Ciudades y Comunidades Sostenibles. Entre las metas del objetivo, la primera que se define es la de “asegurar el acceso de todas las personas a viviendas y servicios básicos adecuados, seguros y asequibles y mejorar los barrios marginales”.

El acceso a servicios básicos adecuados es tanto un derecho fundamental para la vida en las ciudades como un inmenso desafío logístico y económico. Planificadores y decisores políticos se enfrentan a una disyuntiva. Por un lado, promover la densidad habitacional que haga viable y sostenible la inversión necesaria, pública y privada, para la provisión de servicios básicos de calidad que alcance a toda la población. Y por otra parte, garantizar la presencia y accesibilidad de espacios verdes, fundamentales para evitar la degradación ambiental: previenen la formación de islas de calor al interrumpir la masa construida, absorben precipitaciones evitando inundaciones, y mejoran la calidad del aire. 

Estudios recientes también han vinculado la presencia de espacios verdes con un efecto beneficioso sobre diversas dimensiones de la salud pública: salud de embarazadas y recién nacidos, desarrollo cognitivo en infantes, salud mental, reducción de morbilidad cardiovascular, de diabetes tipo 2, e incluso reducción general de mortandad.  

La necesidad de atender y planificar espacios verdes urbanos como factores para el desarrollo sostenible se hace aún más importante ante la creciente evidencia de que funcionan como reductores de la desigualdad. Esto es, que los beneficios para la salud asociados con el acceso a espacios verdes tienen un efecto mayor entre la población socioeconómicamente vulnerable.

En la Argentina, la planificación y evaluación de los efectos de espacios verdes públicos se hace difícil, en particular a escala nacional, ante la inexistencia de información oficial y completa respecto a la calidad, ubicación y extensión de las áreas verdes urbanas, así como de estudios sobre sus efectos.

## Objetivos, actividades e indicadores

### Objetivos específicos

El  proyecto contempla contribuir al abordaje de la problemática desarrollando tres recursos de acceso público:

- Un Atlas de Espacios Verdes en Ciudades Argentinas, consistente en una base de datos georeferenciada con la posición, extensión, nombre y otros atributos de cada uno de los espacios verdes de acceso público presentes en las 155 localidades que en su conjunto forman los 32 grandes aglomerados urbanos en la República Argentina. _Status: completo._

- Un índice de accesibilidad a espacios verdes, georeferenciado en un mapa de alta resolución espacial (a nivel radio censal) cubriendo las 155 localidades que se aglomeran en los principales centros urbanizados del país. Elaborado siguiendo el marco metodológico “10 minute walk”[^1] [^2] [^3], que propone garantizar al 100% de la población urbana acceso a un espacio verde público a 10 minutos de caminata o menos[^4]. _Status: completo._

[^1]: https://www.nrpa.org/our-work/partnerships/initiatives/10-minute-walk/10-minute-walk-commitment-framework/
[^2]: https://10minutewalk.org/
[^3]: http://www.fieldsintrust.org/green-space-index
[^4]: Para un estudio sobre los efectos de la cercania a espacios verdes en el nivel de actividad física de las personas, y del punto de inflexión que representan los 10 minutos de distancia a pie, véase "Quantifying the Contribution of Neighborhood Parks to Physical Activity" https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3800218/


- Un estudio sobre los posibles efectos del acceso a espacios verdes estimando la relación entre accesibilidad, nivel socioeconómico, y dimensiones de la salud como vulnerabilidad sanitaria y mortalidad neonatal. _Status: En ejecución._

### Actividades a realizar para el cumplimiento de objetivos

- Prospección, recolección, limpieza y cruce de fuentes de información georeferenciada con posición y atributos de espacios verdes urbanos. _Status: completo._

- Generación de una base de datos georeferenciada registrando los espacios verdes presentes en las 155 principales localidades urbanizadas de la Argentina. _Status: completo._

- Validación de los resultados mediante control de calidad por contraste con imagen satelital (inspección visual) y consulta con expertos en la materia. _Status: completo._

- Aplicación de técnicas de análisis geoespacial, y cruce con datos censales y de la Encuesta Permanente de Hogares (INDEC) para establecer cantidad de población servida por espacios verdes, distancias de acceso y otros indicadores asociados, con gran resolución espacial (a nivel radio censal). _Status: completo._

- Elaboración de índices de accesibilidad a espacios verdes públicos de acuerdo a la metodología desarrollada por la Unión Europea para sus indicadores de sustentabilidad (European Common Indicators), para cada uno de los centros urbanizados. _Status: completo._

- Establecimiento de un ranking que exprese la situación relativa de las ciudades Argentinas respecto al acceso que brindan a espacios verdes públicos. _Status: Pendiente de ejecución._

- Desarrollo de un paper que reporte métodos empleados y hallazgos resultantes tras el estudio de la distribución del indicador de accesibilidad en la Argentina, y de su correlación con diversos indicadores de salud pública. _Status: En ejecución._

## Entregables

### Atlas de Espacios Verdes en Ciudades Argentinas

La base de datos con los polígonos georeferenciados de los espacios verdes urbanos relevados en el territorio de la República Argentina puede descargarse siguiendo el enlace: __[Base georeferenciada de espacios verdes urbanos publicos en Argentina](https://github.com/bitsandbricks/atlas_espacios_verdes/tree/master/data/processed/osm)__. 


El formato de los datos es ESRI shapefile, que puede ser leído con herramientas con interfaz gráfica de libre acceso como _QGIS_ (www.qgis.org), o con librerías especializadas como `sf` para el lenguaje de programación R (r-spatial.github.io/sf/) y `GeoPandas` para el lenguaje Python (geopandas.org).


## Índice(s) de accesibilidad a espacios verdes

Las métricas de accesibilidad están disponibles en los siguientes enlaces. La estructura de los datos es _csv_ (_comma-separated values_), un formato abierto sencillo para tablas. Puede ser leído con herramientas de ofimática de libre acceso como _LibreOffice_ (libreoffice.org) o cualquier software, lenguaje de programación o librería para análisis de datos.


### Indicadores básicos

- A nivel aglomerado urbano: __[m^2 de espacio verde por habitante (indicador global)](https://raw.githubusercontent.com/bitsandbricks/atlas_espacios_verdes/master/data/processed/metricas/m2_espacio_verde_por_habitante_aglomerados.csv)__

- A nivel localidad: __[m^2 de espacio verde por habitante (indicador global)](https://raw.githubusercontent.com/bitsandbricks/atlas_espacios_verdes/master/data/processed/metricas/accesibilidad_espacios_verdes_localidades.csv)__

### Indicadores avanzados

- A nivel aglomerado urbano: __[porcentaje de la población con acceso a espacios verdes, total de hectáreas accesibles, y m2 accesibles per cápita, por estrato de nivel socioeconómico](https://raw.githubusercontent.com/bitsandbricks/atlas_espacios_verdes/master/data/processed/metricas/accesibilidad_espacios_verdes_aglomerados.csv)__

- A nivel localidad: __[porcentaje de la población con acceso a espacios verdes, total de hectáreas accesibles, y m2 accesibles per cápita, por estrato de nivel socioeconómico](https://raw.githubusercontent.com/bitsandbricks/atlas_espacios_verdes/master/data/processed/metricas/accesibilidad_espacios_verdes_localidades.csv)__

